"use strict";(()=>{var T="S-PScripts",b="chromebook-utilities",E="main",F=`https://api.github.com/repos/${T}/${b}/git/trees/${E}?recursive=1`,a=e=>document.getElementById(e),r={tree:a("folder-tree"),fileList:a("file-list"),breadcrumbs:a("breadcrumbs"),search:a("search-input"),resultCount:a("result-count"),sectionTitle:a("section-title"),modal:a("preview-modal"),modalTitle:a("preview-title"),modalBody:a("preview-body"),openRaw:a("open-raw"),openSite:a("open-site"),copyLink:a("copy-link"),closeModal:a("close-modal")},g=[],l=null,w="",u="";function L(e){return e.split("/").map(n=>encodeURIComponent(n)).join("/")}function N(e){let n={name:"/",children:new Map,files:[]};for(let o of e){let t=n;for(let i of o.dirParts)t.children.has(i)||t.children.set(i,{name:i,children:new Map,files:[]}),t=t.children.get(i);t.files.push(o)}return n}function C(e,n){if(!n)return e;let o=n.split("/").filter(Boolean),t=e;for(let i of o){let s=t.children.get(i);if(!s)return null;t=s}return t}function M(e){let n=[{name:"Home",path:""}],o=e.split("/").filter(Boolean),t="";for(let i of o)t=t?`${t}/${i}`:i,n.push({name:i,path:t});r.breadcrumbs.innerHTML=n.map((i,s)=>`<a href="#" data-path="${i.path}" class="crumb${s===n.length-1?" active":""}">${i.name}</a>`).join('<span class="crumb-sep">/</span>')}function $(e){let n=e.files.length;for(let o of e.children.values())n+=$(o);return n}function k(e,n,o=""){n.innerHTML="";let t=Array.from(e.children.keys()).sort((i,s)=>i.localeCompare(s));for(let i of t){let s=e.children.get(i),p=o?`${o}/${i}`:i,c=document.createElement("li");c.className="tree-item",c.innerHTML=`
      <button class="tree-toggle" aria-label="Toggle folder" aria-expanded="false">\u25B6</button>
      <a href="#" class="tree-folder" data-path="${p}">\u{1F4C1} ${i} <span class="count">${$(s)}</span></a>
      <ul class="tree-children hidden"></ul>
    `;let m=c.querySelector(".tree-toggle"),h=c.querySelector(".tree-children");m.addEventListener("click",()=>{let d=m.getAttribute("aria-expanded")==="true";m.setAttribute("aria-expanded",String(!d)),m.textContent=d?"\u25B6":"\u25BC",h.classList.toggle("hidden",d),!d&&h.childElementCount===0&&k(s,h,p)}),c.querySelector(".tree-folder").addEventListener("click",d=>{d.preventDefault(),v(p)}),n.appendChild(c)}}function x(e){let n=[...e.files];for(let o of e.children.values())n.push(...x(o));return n}function H(e){r.fileList.innerHTML="";let n=u?g.filter(o=>o.name.toLowerCase().includes(u)||o.path.toLowerCase().includes(u)):x(e);r.resultCount.textContent=u?`${n.length} match${n.length===1?"":"es"}`:"",r.sectionTitle.textContent=u?"Search results":e===l?"All files":e.name,n.sort((o,t)=>o.name.localeCompare(t.name)).forEach(o=>{let t=document.createElement("a");t.href=`/${L(o.path)}`,t.target="_blank",t.rel="noopener",t.className="file-item",t.innerHTML=`
        <div class="file-icon">\u{1F4C4}</div>
        <div class="file-meta">
          <div class="file-name" title="${o.name}">${o.name}</div>
          <div class="file-path">/${o.path}</div>
        </div>
        <button class="button small ghost preview-btn" type="button">Preview</button>
      `,t.querySelector(".preview-btn").addEventListener("click",i=>{i.preventDefault(),B(o)}),r.fileList.appendChild(t)})}function v(e){w=e,M(e);let n=C(l,e)??l;H(n)}function B(e){let n=`https://raw.githubusercontent.com/${T}/${b}/${E}/${L(e.path)}`,o=`/${L(e.path)}`;r.modalTitle.textContent=e.name,r.openRaw.href=n,r.openSite.href=o,r.copyLink.onclick=async()=>{try{await navigator.clipboard.writeText(o),r.copyLink.textContent="Copied",setTimeout(()=>r.copyLink.textContent="Copy link",1200)}catch{r.copyLink.textContent="Failed",setTimeout(()=>r.copyLink.textContent="Copy link",1200)}},r.modal.classList.remove("hidden"),r.modal.setAttribute("aria-hidden","false"),r.modalBody.textContent="Loading...",fetch(n).then(t=>t.ok?t.text():Promise.reject(new Error("Failed to load"))).then(t=>r.modalBody.textContent=t).catch(()=>r.modalBody.textContent="Unable to preview this file.")}function f(){r.modal.classList.add("hidden"),r.modal.setAttribute("aria-hidden","true"),r.modalBody.textContent=""}function A(){r.breadcrumbs.addEventListener("click",e=>{let n=e.target.closest("a[data-path]");n&&(e.preventDefault(),v(n.getAttribute("data-path")||""))}),r.search.addEventListener("input",e=>{u=e.target.value.trim().toLowerCase();let n=C(l,w)??l;H(n)}),r.closeModal.addEventListener("click",f),r.modal.addEventListener("click",e=>{e.target===r.modal&&f()}),document.addEventListener("keydown",e=>{e.key==="Escape"&&f()})}async function y(){A(),M("");try{let e=await fetch(F);if(!e.ok)throw new Error("Failed to load repository tree");g=((await e.json()).tree||[]).filter(t=>t.type==="blob"&&t.path.toLowerCase().endsWith(".txt")).map(t=>{let i=t.path.split("/"),s=i[i.length-1],p=i.slice(0,-1);return{path:t.path,name:s,dirParts:p}}),l=N(g),k(l,r.tree,""),v("")}catch(e){console.error(e),r.fileList.innerHTML='<div class="error">Failed to load files. Please try again later.</div>'}}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",y):y();})();
